### ISSUE TITLE
"C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\terraform.exe": file does not exist

### ISSUE THREAD

**Issue by philipstreet-hiscox** [hashicorp/vscode-terraform#338]
Extension Version: 2.0.0-rc1
OS: Windows 10
VSCode version: 1.45.1

When I start VSCode I get a bunch of errors in the Output window indicating that it cannot find terraform.exe;

2020/06/05 15:39:17 exec.go:178: Starting terraform.exe ["terraform" "version"] in "C:\\Users\\xxxxx\\AppData\\Local\\Temp"...
2020/06/05 15:39:17 rpc_logger.go:45: Error for "initialize" (ID 0): [-32098] failed to get version: exec: "C:\\Users\\xxxxx\\AppData\\Local\\Temp\\terraform.exe": file does not exist
2020/06/05 15:39:17 server.go:204: Completed 1 requests [5.0027ms elapsed]
[Error - 15:39:17] Server initialization failed.
  Message: failed to get version: exec: "C:\\Users\\xxxxx\\AppData\\Local\\Temp\\terraform.exe": file does not exist
  Code: -32098 

If I manually copy terraform.exe from the install folder (C:\ProgramData\chocolatey\lib\terraform\tools) and restart VSCode I get a different error;

2020/06/05 15:44:02 exec.go:178: Starting terraform.exe ["terraform" "version"] in "C:\\Users\\xxxxx\\AppData\\Local\\Temp"...
2020/06/05 15:44:02 exec.go:144: Waiting for command to finish ...
2020/06/05 15:44:02 rpc_logger.go:45: Error for "initialize" (ID 0): [-32098] failed to get version: terraform (pid 24016) exited (code 1): exit status 1
stdout: ""
stderr: "Couldn't setup logging tempfile: open C:\\WINDOWS\\terraform-log987382515: Access is denied."
2020/06/05 15:44:02 server.go:204: Completed 1 requests [246.6162ms elapsed]
[Error - 15:44:02] Server initialization failed.
  Message: failed to get version: terraform (pid 24016) exited (code 1): exit status 1
stdout: ""
stderr: "Couldn't setup logging tempfile: open C:\\WINDOWS\\terraform-log987382515: Access is denied."
  Code: -32098

**Comment by paultyng** [comment]
If you run `terraform version` in the Terminal in VS Code in this folder, what output do you get?

**Comment by philipstreet-hiscox** [comment]
@paultyng 

Terraform v0.12.26
+ provider.azuread v0.8.0
+ provider.azurerm v1.44.0

**Comment by philipstreet-hiscox** [comment]
I've tried this on a fresh machine using the latest version (2.0.0-rc.2) with following Terraform versions;

Terraform v0.12.26
+ provider.azuread v0.8.0
+ provider.azurerm v1.44.0

I had to manually copy terraform.exe to the temp folder and do not get the subsequent error about the logging tempfile, but:
- syntax highlighting no longer works in .tfvars files
- Code thinks that all Terraform files (.tf, tfvars) have been updated, even though the diff view shows now changes

**Comment by paultyng** [comment]
I think the logging tempfile issue was resolved in the LS: https://github.com/hashicorp/terraform-ls/issues/141#issuecomment-639685331

The .tfvars highlighting issue is an oversight, I wrote that up in #348 

I'm unable to reproduce the modified bit being shown (I'm also on Windows). This may be related to CRLF settings or something. Can you try disabling the extension and see if it still shows up?

**Comment by philipstreet-hiscox** [comment]
No, disabling didn't fix it, neither did uninstalling the extension.

**Comment by paultyng** [comment]
I think the issue is probably in some other extension then or another issue on disk (like CRLF issues), I don't think the extension itself sets modified in anyway currently.

**Comment by paultyng** [comment]
I'm not seeing this issue pop up elsewhere, and since it recurs while the extension is disabled I don't think its in the code here. Going to close, but if you are able to figure out any additional info on this, happy to run it down further.
